/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 21
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 14
#define ALIAS_COUNT 0
#define TOKEN_COUNT 6
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_DASH_DASH_DASH = 1,
  aux_sym_frontmatter_token1 = 2,
  aux_sym_yaml_content_token1 = 3,
  aux_sym_paragraph_token1 = 4,
  sym_text = 5,
  sym_source_file = 6,
  sym_frontmatter = 7,
  sym_yaml_content = 8,
  sym__block = 9,
  sym_paragraph = 10,
  aux_sym_source_file_repeat1 = 11,
  aux_sym_yaml_content_repeat1 = 12,
  aux_sym_paragraph_repeat1 = 13,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DASH_DASH_DASH] = "---",
  [aux_sym_frontmatter_token1] = "frontmatter_token1",
  [aux_sym_yaml_content_token1] = "yaml_content_token1",
  [aux_sym_paragraph_token1] = "paragraph_token1",
  [sym_text] = "text",
  [sym_source_file] = "source_file",
  [sym_frontmatter] = "frontmatter",
  [sym_yaml_content] = "yaml",
  [sym__block] = "_block",
  [sym_paragraph] = "paragraph",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_yaml_content_repeat1] = "yaml_content_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DASH_DASH_DASH] = anon_sym_DASH_DASH_DASH,
  [aux_sym_frontmatter_token1] = aux_sym_frontmatter_token1,
  [aux_sym_yaml_content_token1] = aux_sym_yaml_content_token1,
  [aux_sym_paragraph_token1] = aux_sym_paragraph_token1,
  [sym_text] = sym_text,
  [sym_source_file] = sym_source_file,
  [sym_frontmatter] = sym_frontmatter,
  [sym_yaml_content] = sym_yaml_content,
  [sym__block] = sym__block,
  [sym_paragraph] = sym_paragraph,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_yaml_content_repeat1] = aux_sym_yaml_content_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DASH_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_frontmatter_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_yaml_content_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_frontmatter] = {
    .visible = true,
    .named = true,
  },
  [sym_yaml_content] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_yaml_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '-') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '-') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '-') ADVANCE(3);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '\r') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(8);
      if (lookahead == '-') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '-') ADVANCE(5);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == '\r') ADVANCE(10);
      if (lookahead == '-') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 11:
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == '\r') ADVANCE(10);
      if (lookahead == '-') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 12:
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead == '\r') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(12);
      END_STATE();
    case 13:
      if (lookahead == '-') ADVANCE(21);
      END_STATE();
    case 14:
      if (lookahead == '-') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      END_STATE();
    case 15:
      if (lookahead == '-') ADVANCE(13);
      END_STATE();
    case 16:
      if (eof) ADVANCE(20);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '\r') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 17:
      if (eof) ADVANCE(20);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 18:
      if (eof) ADVANCE(20);
      if (lookahead == '-') ADVANCE(37);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(18);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 19:
      if (eof) ADVANCE(20);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(19);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_DASH);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_frontmatter_token1);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(9);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_frontmatter_token1);
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead == '\r') ADVANCE(12);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_yaml_content_token1);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_yaml_content_token1);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '-') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_yaml_content_token1);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '-') ADVANCE(5);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_yaml_content_token1);
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == '\r') ADVANCE(10);
      if (lookahead == '-') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '\r') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(33);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '-') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '-') ADVANCE(30);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '\r') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '-') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(39);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(39);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '-') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(39);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(39);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 18},
  [2] = {.lex_state = 19},
  [3] = {.lex_state = 19},
  [4] = {.lex_state = 19},
  [5] = {.lex_state = 19},
  [6] = {.lex_state = 16},
  [7] = {.lex_state = 16},
  [8] = {.lex_state = 16},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 10},
  [11] = {.lex_state = 16},
  [12] = {.lex_state = 17},
  [13] = {.lex_state = 10},
  [14] = {.lex_state = 19},
  [15] = {.lex_state = 19},
  [16] = {.lex_state = 19},
  [17] = {.lex_state = 12},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 14},
  [20] = {.lex_state = 19},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(1),
    [aux_sym_yaml_content_token1] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(18),
    [sym_frontmatter] = STATE(2),
    [sym__block] = STATE(3),
    [sym_paragraph] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(5),
    [sym_text] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      sym_text,
    STATE(4), 3,
      sym__block,
      sym_paragraph,
      aux_sym_source_file_repeat1,
  [12] = 3,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      sym_text,
    STATE(5), 3,
      sym__block,
      sym_paragraph,
      aux_sym_source_file_repeat1,
  [24] = 3,
    ACTIONS(11), 1,
      sym_text,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(5), 3,
      sym__block,
      sym_paragraph,
      aux_sym_source_file_repeat1,
  [36] = 3,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      sym_text,
    STATE(5), 3,
      sym__block,
      sym_paragraph,
      aux_sym_source_file_repeat1,
  [48] = 4,
    ACTIONS(20), 1,
      ts_builtin_sym_end,
    ACTIONS(22), 1,
      aux_sym_paragraph_token1,
    ACTIONS(24), 1,
      sym_text,
    STATE(7), 1,
      aux_sym_paragraph_repeat1,
  [61] = 4,
    ACTIONS(26), 1,
      ts_builtin_sym_end,
    ACTIONS(28), 1,
      aux_sym_paragraph_token1,
    ACTIONS(30), 1,
      sym_text,
    STATE(8), 1,
      aux_sym_paragraph_repeat1,
  [74] = 4,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
    ACTIONS(34), 1,
      aux_sym_paragraph_token1,
    ACTIONS(37), 1,
      sym_text,
    STATE(8), 1,
      aux_sym_paragraph_repeat1,
  [87] = 3,
    ACTIONS(39), 1,
      aux_sym_yaml_content_token1,
    STATE(10), 1,
      aux_sym_yaml_content_repeat1,
    STATE(19), 1,
      sym_yaml_content,
  [97] = 3,
    ACTIONS(41), 1,
      anon_sym_DASH_DASH_DASH,
    ACTIONS(43), 1,
      aux_sym_yaml_content_token1,
    STATE(13), 1,
      aux_sym_yaml_content_repeat1,
  [107] = 2,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 2,
      aux_sym_paragraph_token1,
      sym_text,
  [115] = 3,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 1,
      aux_sym_frontmatter_token1,
    ACTIONS(49), 1,
      sym_text,
  [125] = 3,
    ACTIONS(51), 1,
      anon_sym_DASH_DASH_DASH,
    ACTIONS(53), 1,
      aux_sym_yaml_content_token1,
    STATE(13), 1,
      aux_sym_yaml_content_repeat1,
  [135] = 2,
    ACTIONS(26), 1,
      ts_builtin_sym_end,
    ACTIONS(56), 1,
      sym_text,
  [142] = 2,
    ACTIONS(56), 1,
      sym_text,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
  [149] = 1,
    ACTIONS(60), 2,
      ts_builtin_sym_end,
      sym_text,
  [154] = 1,
    ACTIONS(62), 1,
      aux_sym_frontmatter_token1,
  [158] = 1,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
  [162] = 1,
    ACTIONS(66), 1,
      anon_sym_DASH_DASH_DASH,
  [166] = 1,
    ACTIONS(56), 1,
      sym_text,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 12,
  [SMALL_STATE(4)] = 24,
  [SMALL_STATE(5)] = 36,
  [SMALL_STATE(6)] = 48,
  [SMALL_STATE(7)] = 61,
  [SMALL_STATE(8)] = 74,
  [SMALL_STATE(9)] = 87,
  [SMALL_STATE(10)] = 97,
  [SMALL_STATE(11)] = 107,
  [SMALL_STATE(12)] = 115,
  [SMALL_STATE(13)] = 125,
  [SMALL_STATE(14)] = 135,
  [SMALL_STATE(15)] = 142,
  [SMALL_STATE(16)] = 149,
  [SMALL_STATE(17)] = 154,
  [SMALL_STATE(18)] = 158,
  [SMALL_STATE(19)] = 162,
  [SMALL_STATE(20)] = 166,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [20] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1, 0, 0),
  [22] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [24] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 1, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 2, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_yaml_content, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 4, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_frontmatter, 4, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_yaml_content_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_yaml_content_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 5, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [64] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_markdoc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "markdoc",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
